//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeylaninMutfagi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tatli
    {
        public int tatliID { get; set; }
        public string tatliAdi { get; set; }
        public string malzemeler { get; set; }
        public string yapilisi { get; set; }
        public Nullable<int> tKategoriID { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<int> populerlik { get; set; }
    
        public virtual tatliKategori tatliKategori { get; set; }
    }
}
